### ISSUE TITLE
Some chars need to be escaped

### ISSUE THREAD

**Issue by Goooler** [ffurrer2/extract-release-notes#349]
My changelog looks like this:

```md
### Added
* In order to use `custom`, you must now use Gradle 8.0+.
```

I use this action to pick it and release it like:

```yml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
      - name: Create release
        run: gh release create --title ${{ github.ref_name }} --notes '${{ steps.extract-release-notes.outputs.release_notes }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and the errors will show:

```sh
/home/runner/work/_temp/b424905f-a1d2-4aef-ba90-8f409d60cac5.sh: line 2: custom: command not found
```

in this case, I tried to write the output into a file and pick the file from GH CLI like:

```yaml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
      - name: Write release note into a file
        run: echo "${{ steps.extract-release-notes.outputs.release_notes }}" > release_notes.txt
      - name: Create release
        run: gh release create --title ${{ github.ref_name }} --notes-file release_notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The same error shown. I believe we have to escape "`" in my example and write it to a file:

```sh
echo "### Added\n* In order to use \`custom\`, you must now use Gradle 8.0+.\n" > note.txt

cat note.txt

### Added
* In order to use `custom`, you must now use Gradle 8.0+.
```
